#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
# The redirection must be a “301 Moved Permanently”

# Define the string "Hello World!" to write to the default index page.
STRING="Hello World!"

# Define the redirection configuration for Nginx.
REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://github.com/nitoua-21; \n\t}\n"

# Specify the Nginx configuration file path.
FILE="/etc/nginx/sites-available/default"
ERRORFILE="/usr/share/nginx/html/404error.html"
ERRORSTRING="Ceci n'est pas une page"
ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
HEADERSTRING="\n\tadd_header X-Served-By $HOSTNAME;\n"

# Update the package list.
apt-get -y update

# Install Nginx.
apt-get -y install nginx

# Allow HTTP traffic through the firewall.
ufw allow 'Nginx HTTP'

# Write "Hello World!" to the default Nginx index page.
echo "$STRING" > /var/www/html/index.nginx-debian.html

# Insert the redirection rule into the Nginx configuration file at line 53
sed -i "53i\ $REDIRECT" "$FILE"

echo "$ERRORSTRING" > "$ERRORFILE"
sed -i "53i\ $ERRORREDIRECT" "$FILE"

# Add custom header X-Served-By
sed -i "40i\ $HEADERSTRING" "$FILE"

# Restart the Nginx service to apply the changes.
service nginx restart

echo -e "\nDone.\n"